<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net48</TargetFramework><LangVersion>7.3</LangVersion>
    <AssemblyName>WpeDataOracle</AssemblyName><AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**;bin\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="WinsockPacketEditor"><HintPath>$(OriginalBin)\WinsockPacketEditor.exe</HintPath></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(OriginalBin)\Newtonsoft.Json.dll</HintPath></Reference>
  </ItemGroup>
</Project>
